DATASET:
  TYPE: CUHK_SYSU
  PATH: !include configs/_path_cuhk_sysu.yaml
  BATCH_SIZE: 5
SOLVER:
  MAX_EPOCHS: 20
  OPTIMIZER: 'SGD'
  BASE_LR: 0.003
  WEIGHT_DECAY: 0.0005
  BIAS_LR_FACTOR: 1.
  BIAS_DECAY: 0.0005
  SGD_MOMENTUM: 0.9
  LR_DECAY_MILESTONES: [10, 14]
  LR_DECAY_GAMMA: 0.1
MODEL:
  BACKBONE: 'ResNet'
  REID:
    LOSS:
      LUT_SIZE: 5532
      CQ_SIZE: 5000
      MARGIN: 0.25
  PARAM_INIT: 'v1'
